-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 09:34:07 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema market
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `market` DEFAULT CHARACTER SET utf8mb3 ;
USE `market` ;

-- -----------------------------------------------------
-- Table `market`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`authors` (
  `id_author` INT NOT NULL AUTO_INCREMENT,
  `second_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `country` VARCHAR(30) NOT NULL DEFAULT 'Россия',
  PRIMARY KEY (`id_author`),
  UNIQUE INDEX `fullname UNIQUE` (`second_name` ASC, `first_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `market`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`books` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `genre` ENUM('проза', 'поэзия', 'другое') NOT NULL DEFAULT 'проза',
  `price` DECIMAL(6,2) UNSIGNED NOT NULL DEFAULT '0.00',
  `weight` DECIMAL(4,3) UNSIGNED NOT NULL DEFAULT '0.000',
  `pages_count` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `publish_year` SMALLINT NULL DEFAULT NULL,
  `id_author` INT NOT NULL,
  PRIMARY KEY (`id_book`),
  INDEX `fk_books_authors_idx` (`id_author` ASC) VISIBLE,
  CONSTRAINT `fk_books_authors`
    FOREIGN KEY (`id_author`)
    REFERENCES `market`.`authors` (`id_author`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `market`.`booksinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`booksinfo` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `second_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `publish_year` SMALLINT NULL DEFAULT NULL,
  `price` DECIMAL(6,2) UNSIGNED NOT NULL DEFAULT '0.00',
  `coming_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_book`),
  UNIQUE INDEX `title_first_name_second_name` (`title` ASC, `second_name` ASC, `first_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `market`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`customers` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `second_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_customer`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `fullname UNIQUE` (`second_name` ASC, `first_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `market`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_customer` INT NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_orders_customers1_idx` (`id_customer` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `market`.`customers` (`id_customer`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `market`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`content` (
  `id_order` INT NOT NULL,
  `id_book` INT NOT NULL,
  `count` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_order`, `id_book`),
  INDEX `fk_orders_has_books_books1_idx` (`id_book` ASC) VISIBLE,
  INDEX `fk_orders_has_books_orders1_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_books_books1`
    FOREIGN KEY (`id_book`)
    REFERENCES `market`.`books` (`id_book`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_has_books_orders1`
    FOREIGN KEY (`id_order`)
    REFERENCES `market`.`orders` (`id_order`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `market`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`games` (
  `idGame` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `category` VARCHAR(50) NOT NULL,
  `price` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`idGame`),
  FULLTEXT INDEX `description` (`description`) VISIBLE,
  FULLTEXT INDEX `description_name` (`name`, `description`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `market`.`myeventtable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`myeventtable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_time` DATETIME NOT NULL,
  `event_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `market`.`tempbooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`tempbooks` (
  `second_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `price` DECIMAL(6,2) NOT NULL DEFAULT '0.00')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `market`.`video_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`video_games` (
  `Title` VARCHAR(200) NULL DEFAULT NULL,
  `MaxPlayers` TINYINT NULL DEFAULT NULL,
  `Genres` VARCHAR(100) NULL DEFAULT NULL,
  `Release Console` VARCHAR(100) NULL DEFAULT NULL,
  `ReleaseYear` SMALLINT NULL DEFAULT NULL,
  FULLTEXT INDEX `genres` (`Genres`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
