-- MySQL Workbench Synchronization
-- Generated: 2026-04-27 09:45
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: 221

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `market`.`shipment` (
  `id_shipment` INT(11) NOT NULL AUTO_INCREMENT,
  `count` TINYINT(4) NOT NULL,
  `shipment_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_book` INT(11) NOT NULL,
  PRIMARY KEY (`id_shipment`),
  INDEX `fk_shipment_books1_idx` (`id_book` ASC) VISIBLE,
  CONSTRAINT `fk_shipment_books1`
    FOREIGN KEY (`id_book`)
    REFERENCES `market`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
